### ISSUE TITLE
Migrate from Highlight.js to CodeMirror

### ISSUE THREAD

**Issue by zenorocha** [liferay/electric#4]
We have few problems with Highlight.js today.

1) It only renders on Markdown files 
2) It doesn't support Soy highlighting

Although I love the fact that we have server-side highlighting, I believe we can't use Highlight.js anymore :/

The only solution I see is to migrate to CodeMirror. We use that already for http://metaljs.com/docs because of the Soy highlighting and it works fine.

What do you think?

**Comment by Robert-Frampton** [comment]
Yeah we can migrate to it. It's a little bit overkill to have a full blown editor, but if we want Soy syntax highlighting I don't think there are any other options.

**Comment by zenorocha** [comment]
Yeah :/

**Comment by zenorocha** [comment]
https://github.com/liferay/electric/commit/797cc4be23e6110a04c01b540c66aa0ce957e69c
